# -----------------------------------------------------------------------------
#  pytermor [ANSI formatted terminal output toolset]
#  (c) 2022. A. Shavykin <0.delameter@gmail.com>
# -----------------------------------------------------------------------------
# AUTOGENERATED MODULE
# %t
"""
Color preset list.
"""
from .color import Color16, Color256, ColorRGB
from .ansi import IntCode


class CVAL:
    """

    """
    # fmt: off
%s
    # fmt: on
